// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: currencies.sql

package database

import (
	"context"
)

const validateCurrency = `-- name: ValidateCurrency :one
SELECT EXISTS(SELECT 1 FROM supported_currencies WHERE code = $1 AND active = true)
`

func (q *Queries) ValidateCurrency(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, validateCurrency, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
