// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID               string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	Type             string
	Subtype          sql.NullString
	Mask             sql.NullString
	OfficialName     sql.NullString
	AvailableBalance sql.NullString
	CurrentBalance   sql.NullString
	IsoCurrencyCode  sql.NullString
	ItemID           string
	UserID           uuid.UUID
}

type Delegation struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	IsRevoked bool
	LastUsed  time.Time
}

type PlaidItem struct {
	ID                    string
	UserID                uuid.UUID
	AccessToken           string
	InstitutionName       string
	Nickname              sql.NullString
	TransactionSyncCursor sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type PlaidWebhookRecord struct {
	ID          uuid.UUID
	WebhookType string
	WebhookCode string
	ItemID      string
	UserID      uuid.UUID
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID           uuid.UUID
	HashedToken  string
	UserID       uuid.UUID
	DelegationID uuid.UUID
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IsUsed       bool
	UsedAt       sql.NullTime
}

type Transaction struct {
	ID                      string
	AccountID               string
	Amount                  string
	IsoCurrencyCode         sql.NullString
	Date                    sql.NullTime
	MerchantName            sql.NullString
	PaymentChannel          string
	PersonalFinanceCategory string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type User struct {
	ID             uuid.UUID
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	Email          string
	IsVerified     sql.NullBool
	IsMember       bool
	FreeCalls      int32
}

type VerificationRecord struct {
	UserID           uuid.UUID
	VerificationCode string
	ExpiryTime       time.Time
}
