// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    uuid.UUID
}

type Delegation struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	RevokedAt sql.NullTime
	IsRevoked bool
	LastUsed  time.Time
}

type RefreshToken struct {
	ID           uuid.UUID
	HashedToken  string
	DelegationID uuid.UUID
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IsUsed       bool
	UsedAt       sql.NullTime
}

type SupportedCurrency struct {
	Code   string
	Name   string
	Active bool
}

type Transaction struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Amount          string
	Category        string
	Description     sql.NullString
	TransactionDate time.Time
	TransactionType string
	CurrencyCode    string
	AccountID       uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
