// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plaid_webhook_records.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlaidWebhookRecord = `-- name: CreatePlaidWebhookRecord :one
INSERT INTO plaid_webhook_records(id, webhook_type, webhook_code, item_id, user_id, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
RETURNING id, webhook_type, webhook_code, item_id, user_id, created_at
`

type CreatePlaidWebhookRecordParams struct {
	ID          uuid.UUID
	WebhookType string
	WebhookCode string
	ItemID      string
	UserID      uuid.UUID
}

func (q *Queries) CreatePlaidWebhookRecord(ctx context.Context, arg CreatePlaidWebhookRecordParams) (PlaidWebhookRecord, error) {
	row := q.db.QueryRowContext(ctx, createPlaidWebhookRecord,
		arg.ID,
		arg.WebhookType,
		arg.WebhookCode,
		arg.ItemID,
		arg.UserID,
	)
	var i PlaidWebhookRecord
	err := row.Scan(
		&i.ID,
		&i.WebhookType,
		&i.WebhookCode,
		&i.ItemID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
