// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plaid_items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO plaid_items(id, user_id, item_id, access_token, request_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, user_id, item_id, access_token, request_id, created_at, updated_at
`

type CreateItemParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ItemID      string
	AccessToken string
	RequestID   sql.NullString
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (PlaidItem, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.UserID,
		arg.ItemID,
		arg.AccessToken,
		arg.RequestID,
	)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.AccessToken,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, user_id, item_id, access_token, request_id, created_at, updated_at FROM plaid_items
WHERE user_id = $1
`

func (q *Queries) GetAccessToken(ctx context.Context, userID uuid.UUID) (PlaidItem, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken, userID)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.AccessToken,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
