// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plaid_webhook_records.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlaidWebhookRecord = `-- name: CreatePlaidWebhookRecord :one
INSERT INTO plaid_webhook_records(id, webhook_type, webhook_code, item_id, user_id, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
RETURNING id, webhook_type, webhook_code, item_id, user_id, created_at
`

type CreatePlaidWebhookRecordParams struct {
	ID          uuid.UUID
	WebhookType string
	WebhookCode string
	ItemID      string
	UserID      uuid.UUID
}

func (q *Queries) CreatePlaidWebhookRecord(ctx context.Context, arg CreatePlaidWebhookRecordParams) (PlaidWebhookRecord, error) {
	row := q.db.QueryRowContext(ctx, createPlaidWebhookRecord,
		arg.ID,
		arg.WebhookType,
		arg.WebhookCode,
		arg.ItemID,
		arg.UserID,
	)
	var i PlaidWebhookRecord
	err := row.Scan(
		&i.ID,
		&i.WebhookType,
		&i.WebhookCode,
		&i.ItemID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookRecord = `-- name: DeleteWebhookRecord :exec
DELETE FROM plaid_webhook_records
WHERE user_id = $1 AND item_id = $2
`

type DeleteWebhookRecordParams struct {
	UserID uuid.UUID
	ItemID string
}

func (q *Queries) DeleteWebhookRecord(ctx context.Context, arg DeleteWebhookRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookRecord, arg.UserID, arg.ItemID)
	return err
}

const getWebhookRecord = `-- name: GetWebhookRecord :many
SELECT id, webhook_type, webhook_code, item_id, user_id, created_at FROM plaid_webhook_records
WHERE user_id = $1 AND item_id = $2
`

type GetWebhookRecordParams struct {
	UserID uuid.UUID
	ItemID string
}

func (q *Queries) GetWebhookRecord(ctx context.Context, arg GetWebhookRecordParams) ([]PlaidWebhookRecord, error) {
	rows, err := q.db.QueryContext(ctx, getWebhookRecord, arg.UserID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidWebhookRecord
	for rows.Next() {
		var i PlaidWebhookRecord
		if err := rows.Scan(
			&i.ID,
			&i.WebhookType,
			&i.WebhookCode,
			&i.ItemID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
