// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: error_logs.sql

package database

import (
	"context"
)

const createErrorLog = `-- name: CreateErrorLog :exec
INSERT INTO error_logs (timestamp, command, error_message)
VALUES (?, ?, ?)
RETURNING id, timestamp, command, error_message
`

type CreateErrorLogParams struct {
	Timestamp    string
	Command      string
	ErrorMessage string
}

func (q *Queries) CreateErrorLog(ctx context.Context, arg CreateErrorLogParams) error {
	_, err := q.db.ExecContext(ctx, createErrorLog, arg.Timestamp, arg.Command, arg.ErrorMessage)
	return err
}
