name: Backend Deployment

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/BACKEND_CD.yml'

jobs:
  deploy-backend:
    name: Deploy
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.0"

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: greed-468623

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -f backend/Dockerfile -t us-central1-docker.pkg.dev/greed-468623/greed-ar-repo/greed:latest .

    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/greed-468623/greed-ar-repo/greed:latest
      
    - name: Create env file
      run: |
        cat > env.yaml << EOF
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        STATIC_ASSETS_PATH: ${{ vars.STATIC_ASSETS_PATH }}
        JWT_ISSUER: ${{ vars.JWT_ISSUER }}
        JWT_AUDIENCE: ${{ vars.JWT_AUDIENCE }}
        JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REFRESH_EXPIRATION: ${{ vars.REFRESH_EXPIRATION }}
        RATE_LIMIT: ${{ vars.RATE_LIMIT }}
        RATE_REFRESH: ${{ vars.RATE_REFRESH }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        GREED_EMAIL: ${{ vars.GREED_EMAIL }}
        PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
        PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        PLAID_SANDBOX: ${{ secrets.PLAID_SANDBOX }}
        PLAID_WEBHOOK_URL: ${{ secrets.PLAID_WEBHOOK_URL }}
        AES_KEY: ${{ secrets.AES_KEY }}
        EOF

    - name: Install goose
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: Setup Cloud SQL Proxy
      run: |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=greed-468623:us-central1:greed-db=tcp:5432 &
        sleep 10 

    - name: Create application database
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        psql "postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/postgres" -c "CREATE DATABASE \"greed-db\";" || echo "Database already exists, continuing..."
    
    - name: Run database migrations
      run:  goose -dir backend/sql/schema postgres "${{ secrets.MIGRATION_DB_URL }}" up

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy greed \
          --image us-central1-docker.pkg.dev/greed-468623/greed-ar-repo/greed:latest \
          --region us-central1 \
          --allow-unauthenticated \
          --project greed-468623 \
          --add-cloudsql-instances greed-468623:us-central1:greed-db \
          --env-vars-file env.yaml      