name: CLI Deployment

on:
  push:
    branches: [main]
    paths:
      - 'cli**'
      - '.github/workflows/CLI_CD.yml'

jobs:
  dockerize-cli:
    name: Dockerize CLI
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.0"

    - name: Build Docker image
      run: docker build -t greed-cli:latest -f cli/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag image for Docker Hub
      run: docker tag greed-cli:latest jmsguy/greed-cli:latest

    - name: Push to Docker Hub
      run: docker push jmsguy/greed-cli:latest

